In [ ]:
# Numypy -> USed in a lot of areas ML, AI etc
# It contains both python objects such as lists and other containers
# dictionaries and number objects such as integers and floating points
# Numpy itself adds  an extension package to Python for multidimensional arrays
# This is closer to the hardware for better efficiency and is designed for scientific computing


In [5]:
import numpy as np
# This is list being taken in and is represented internally as a Numpy array
# The output looks like a list but is a numpy array
a = np.array([0, 1, 2, 3,])
print(a)

[0 1 2 3]


In [4]:
# This creates a Numpy array
# Will print 0 - 9
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [3]:
# Numpy has memory-efficient containers that provide fast numerical operations
# Lists
L = range(1000)
# The square of each number in the range is passed through a for loop
# This creates a new list which holds all the squared values
# The %timeit function measures iteration time
%timeit [i**2 for i in L]

246 µs ± 4.54 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [6]:
# This Numpy array is about 200 times quicker than the non Numpy example above
a = np.arange(1000)
%timeit a**2

1.88 µs ± 22 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [7]:
# Creating Arrays
# Manually 
# 1 Dimension array
a = np.array([0, 1, 2, 3])
a

array([0, 1, 2, 3])

In [8]:
# Print array dimensions
a.ndim

1

In [9]:
# Print array shape
a.shape

(4,)

In [10]:
# Array length
len(a)

4

In [11]:
# 2D Arrays
b = np.array([[0, 1, 2], [3, 4, 5]])
b

array([[0, 1, 2],
       [3, 4, 5]])

In [12]:
b.ndim

2

In [15]:
# In order of rows and columns
b.shape

(2, 3)

In [16]:
# This returns the length of the first dimension
len(b)

2

In [17]:
# Multidimensional Arrays
c = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
c

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [18]:
c.ndim

2

In [19]:
# In order of rows and columns
c.shape

(4, 2)

In [20]:
len(c)

4

In [21]:
# Multidimensional Arrays
d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]])
d

SyntaxError: closing parenthesis ')' does not match opening parenthesis '[' (<ipython-input-21-caed5a4bfcb2>, line 2)