In [1]:
import numpy as np

In [2]:
# Logical Operations
a = np.array([1, 1, 0, 0], dtype=bool)
b = np.array([1, 0, 1, 0], dtype=bool)

# Perform a logical OR comparing the 2 arrays
np.logical_or(a, b)

array([ True,  True,  True, False])

In [3]:
# Perform a logical AND comparing the 2 arrays
np.logical_or(a, b)

array([ True,  True,  True, False])

In [4]:
# Transcendental functions
a = np.arange(5)

# Find the sin value of each of elements
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [7]:
# Find the log value of each element
# There will be a divide by zero error encountered
np.log(a)

<ipython-input-7-c4e84278d7a6>:2: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [8]:
# Will evaluate e ^ x for each element in the created array
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [9]:
# Reductions
x = np.array([1, 2, 3, 4])

# adds all the elements in the array
np.sum(x)

10

In [10]:
# Sum by rows and columns
x = np.array([[1, 1], [2, 2]])
x

array([[1, 1],
       [2, 2]])

In [11]:
# Adds the columns which is the first dimension
x.sum(axis=0)

array([3, 3])

In [12]:
# Adds the rows which is the second dimension
x.sum(axis=1)

array([2, 4])

In [13]:
# Find the minimum value
x = np.array([1, 2, 3, 4])
x.min()

1

In [14]:
# Find the maximum value
x = np.array([1, 2, 3, 4])
x.max()

4

In [15]:
# Find the index maximum value
x = np.array([1, 4, 3, 2])
x.argmax()

1