In [1]:
import numpy as np

In [2]:
# Create an array using the diag function
# This will use the specified values on the diagonal
# and zeros elsewhere
a = np.diag([1, 2, 3, 4])
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [3]:
# Extract the diagonal
np.diag(a)

array([1, 2, 3, 4])

In [4]:
# Create an array, the shape is specified and returns a sample from the standard normal variable
# This will be uniform random
b = np.random.randn(4)
b

array([-0.21934017,  0.20168123, -0.16940007, -1.01797257])

In [5]:
# Datatypes
# dtype will show the type of the data being used
a = np.arange(10)
a.dtype

dtype('int32')

In [7]:
# dtype can also be used to explicitly set the data type
b = np.arange(10, dtype='float64')
b

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [10]:
# Datatype for zeros and ones is by default float
c = np.zeros((5, 5))
print(c)
c.dtype

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


dtype('float64')

In [12]:
# Complex datatype
# Useful for complex numbers but not used too much
d = np.array([1+2j, 2+4j])
d
d.dtype

dtype('complex128')

In [14]:
# Boolean datatype
e = np.array([True, False, True, False, True])
e.dtype

dtype('bool')

In [20]:
# String datatype
# Will return <U for unicode
f = np.array(["Bob", "Bill", "Barry"])
f.dtype

dtype('<U5')