In [1]:
import numpy as np

In [2]:
# Copies and Views
# Slicing creates a view on the original array
# This is just a way of accessing the array's data
# This means that the original array is mot copied in memory
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# Goes from beginning to end insteps of 2
b = a[::2]
b

array([0, 2, 4, 6, 8])

In [4]:
# Checks if 2 arrays share the same memory block
np.shares_memory(a, b)

True

In [5]:
b[0] = 10
b

array([10,  2,  4,  6,  8])

In [6]:
# The array a created previous was modified by setting the value in b
# This is a and b share the same memory
a

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [7]:
a = np.arange(10)

# Force a copy
c = a[::2].copy()
c

array([0, 2, 4, 6, 8])

In [8]:
# Will be false as c is a forced copy and not the same object
np.shares_memory(a, c)

False

In [9]:
# a will not be updated as a and c afe different memory blocks
c[0] = 10
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
#Fancy indexing
# Numpy arrays can be indexed with slices but not just them
# Using boolean or integer arrays is called fancy indexing and creates copies not views
a = np.random.randint(0, 20, 15)
a

array([ 6,  3, 14, 10, 12,  0,  3, 10,  0, 18, 11,  9, 10, 16,  7])

In [11]:
# Using a boolean mask
# in this case to find even numbers
mask = (a % 2 == 0)

In [12]:
# Using the extract_from function to pull out values
extract_from_a = a[mask]
extract_from_a

array([ 6, 14, 10, 12,  0, 10,  0, 18, 10, 16])

In [13]:
# Using a mask to index can be very helpful when assigning a new value to a sub-array
a[mask] = -1
a

array([-1,  3, -1, -1, -1, -1,  3, -1, -1, -1, 11,  9, -1, -1,  7])

In [18]:
# Index with an integer array
a = np.arange(0, 100, 10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [24]:
a[[2, 3, 2, 4, 2]]


array([20, 30, 20, 40, 20])

In [25]:
# Assign new values
a[[9, 7]] = -200
a

array([   0,   10,   20,   30,   40,   50,   60, -200,   80, -200])