In [1]:
import numpy as np

In [2]:
# Using arange function
# arange is an array-valued version of Python ranges
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# Create a smart array with steps
b = np.arange(1, 10, 2)
b

array([1, 3, 5, 7, 9])

In [5]:
# An array using linspace
# This will be the start end and number of points
a = np.linspace(0, 10, 5)
a

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [6]:
# Common arrays
# Will generate a 5 * 5 array of all values 1
a = np.ones((5, 5))
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
# Same as above but with zeroes
b = np.zeros((5, 5))
b

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
# Returns a 2D array with ones on the diagonal and zeros otherwise
c = np.eye(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
# Similar to above but with 3 rows and 2 columns
d = np.eye(3, 4)
d

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [12]:
# Create an array using the diag function
# This will use the specified values on the diagonal
# and zeros elsewhere
e = np.diag([1, 2, 3, 4])
e

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [13]:
# Create an array, the shape is specified and it is filled with random values
f = np.random.rand(4)
f

array([0.73417025, 0.90299052, 0.09894861, 0.57080529])