In [1]:
import numpy as np

In [3]:
# Indexing
# Indices begin at 0 (Like other languages)
a = np.arange(10)
print(a[5])

5


In [4]:
# Multidimensional arrays
# Indexes in this case are tuples of integers
b = np.diag([1, 2, 3])
print(b[2, 2])

3


In [7]:
# Assigns a value to a specific location
b[2, 1] = 5
b

array([[1, 0, 0],
       [0, 2, 0],
       [0, 5, 3]])

In [8]:
# Slicing
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
# This is the starting point, endpoint and steps
a[1:8:2]

array([1, 3, 5, 7])

In [12]:
# Arrangment and slicing can be combined
# The value 10 will be inserted from position 5 upwards
b = np.arange(10)
b[5:] = 10
b

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [13]:
# This will reassign the second 5 values to reverse the first 5
c = np.arange(5)
b[5:] = c[::-1]
b

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])