In [1]:
import numpy as np

In [2]:
#Scalar ops
a = np.array([1, 2, 3, 4])
# Will add 1 to each value in the array
a + 1

array([2, 3, 4, 5])

In [3]:
# Squares each array value
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [5]:
# The arithmetic perfored is performed elementwise
# Create an array of ones and increment and subtract 
# the values from the same placed value in the original array
b = np.ones(4) + 1
a - b

array([-1.,  0.,  1.,  2.])

In [6]:
a * b

array([2., 4., 6., 8.])

In [7]:
# Matrix multiplication
c = np.diag([1, 2, 3, 4])
print(c * c)
print("=================")
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [8]:
# Comparing arrays
# Compares the values in the correspoding positions in the array eg a0 and b0
a = np.array([1, 2, 3, 4])
b = np.array([5, 2, 2, 4])
a == b

array([False,  True, False,  True])

In [11]:
# Array-wise comparisons
a = np.array([1, 2, 3, 4])
b = np.array([5, 2, 2, 4])
c = np.array([1, 2, 3, 4])

# Will be false
np.array_equal(a, b)

False

In [12]:
# Will be true
np.array_equal(a, c)

True

In [ ]:
#Logical Operations
